modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL="https://github.com/Vonr/Ars-Unification/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL = "https://github.com/Vonr/Ars-Unification" #optional
logoFile="ars_unification.png"
credits="Authors of Ars Nouveau, Ars Omega, Not Enough Glyphs, Actually Additions, Ender IO, Farmer's Delight, Immersive Engineering, Integrated Dynamics, Mekanism, Modern Industrialization, and Occultism"
authors = "${mod_authors}"

description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"


[[dependencies."${mod_id}"]]
modId="ars_nouveau"
type="required"
versionRange="${ars_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "ars-nouveau"
    curseforge = "ars-nouveau"


[[dependencies."${mod_id}"]]
modId="not_enough_glyphs"
type="optional"
versionRange="${neg_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    # modrinth = "not-enough-glyphs"
    curseforge = "not-enough-glyphs"


[[dependencies."${mod_id}"]]
modId="mekanism"
type="optional"
versionRange="${mekanism_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "mekanism"
    curseforge = "mekanism"


[[dependencies."${mod_id}"]]
modId="enderio_machines"
type="optional"
versionRange="${enderio_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "enderio"
    curseforge = "ender-io"


[[dependencies."${mod_id}"]]
modId="immersiveengineering"
type="optional"
versionRange="${immersive_engineering_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "immersiveengineering"
    curseforge = "immersive-engineering"


[[dependencies."${mod_id}"]]
modId="integrateddynamics"
type="optional"
versionRange="${integrateddynamics_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "integrated-dynamics"
    curseforge = "integrated-dynamics"


[[dependencies."${mod_id}"]]
modId="actuallyadditions"
type="optional"
versionRange="${actuallyadditions_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "actually-additions"
    curseforge = "actually-additions"


[[dependencies."${mod_id}"]]
modId="modern_industrialization"
type="optional"
versionRange="${modern_industrialization_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "modern-industrialization"
    curseforge = "modern-industrialization"


[[dependencies."${mod_id}"]]
modId="occultism"
type="optional"
versionRange="${occultism_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "occultism"
    curseforge = "occultism"


[[dependencies."${mod_id}"]]
modId="farmersdelight"
type="optional"
versionRange="${farmers_delight_version_range}"
ordering="AFTER"
side="BOTH"
    [dependencies."${mod_id}".mc-publish]
    modrinth = "farmers-delight"
    curseforge = "farmers-delight"
